- name: check mysql is installed
  command: which mysql
  ignore_errors: true
  changed_when: false
  register: mysql_installed

- name: mysql install
  yum: name={{ item }} state=installed
  with_items:
    - mysql
    - mysql-server
    - mysql-devel
    - MySQL-python

- name: mysqld is running and enabled
  service: name=mysqld state=running enabled=yes

- name: get mysql password
  shell: cat /root/.mysql_secret | awk '{print $18}'
  register: mysql_root_password
  when: mysql_installed|failed

- name: set root password file
  template: src=my.cnf_root.j2 dest=/root/.my.cnf owner=root mode=0600
  when: mysql_installed|failed

- name: set mysql password
  command: mysqladmin -u root password {{ db_user_password }}
  when: mysql_installed|failed

- name: remove root password file
  file: path=/root/.my.cnf state=absent
  when: mysql_installed|failed

- name: set mysql config
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root mode=0600 backup=yes
  notify: restart mysql

- name: delete test database
  mysql_db: login_user=root login_password={{ db_user_password }} name=test state=absent

- name: create application user
  mysql_user: login_user=root login_password={{ db_user_password }} name={{ db_application_user}} password={{ db_application_password }} host={{ item }} priv=*.*:ALL state=present
  with_items:
    - "{{ groups.application }}"
