- name: passenger install
  stat: path=/usr/local/lib/ruby/gems/2.2.0/gems/passenger-5.0.24/buildout/apache2/mod_passenger.so
  register: passenger_installed

- name: passenger-module install
  command: "{{ ruby_command_path }}/passenger-install-apache2-module --auto --languages=ruby,python"
  when: not passenger_installed.stat.exists
