- name: passenger install
  gem: name=passenger state=present executable={{ ruby_command_path }}/gem user_install=no
  register: passenger_installed

- name: passenger-module install
  command: "{{ ruby_command_path }}/passenger-install-apache2-module --auto --languages=ruby,python"
  when: passenger_installed.changed
